# Developed for the Alif Semiconductor platform. Published by Sirin Software
# as a collaboration snapshot.
#
# This repository combines material under several licences; see README.md,
# LICENSE-MIT.txt, LICENSE-ALIF.txt and THIRD_PARTY_NOTICES.txt.

CONFIG_GPIO=y
CONFIG_FPU=y
CONFIG_NO_OPTIMIZATIONS=y
CONFIG_UART_INTERRUPT_DRIVEN=y

